### ISSUE TITLE
Custom lando file

### ISSUE THREAD

**Issue by fembuelita** [pantheon-systems/localdev-issues#18]
Is it possible to use a custom lando file? I was imagining to use this tool as a nice GUI to replace some of the existing CLI infrastructure I have, but I can't tell if my custom lando files are working here. For example, using PHPStorm/xDebug together is very helpful for local development to add breakpoints and such. Sample lando file attached.

```yml
name: {{my-pantheon-site-name}}
recipe: pantheon
config:
  framework: wordpress
  site: {{my-pantheon-site-name}}
  id: {{redactred}}
  xdebug: true

services:
  appserver:
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName={{my-pantheon-site-name}}.lndo.site"


  # Add a phpmyadmin db frontend
  pma:

    # Use the latest version of phpmyadmin
    type: phpmyadmin

    # The databases you want to look at, this will default to a service called
    # "database"
    #
    # You might want to run `lando info` on your app to see what databases you
    # have available
    hosts:
      - database

# Add in a proxy route to phpmyadmin
proxy:
  pma:
    - pma.{{my-pantheon-site-name}}.lndo.site
```
